# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(530, 408)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 511, 381))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tentnoBar = QtWidgets.QScrollBar(parent=self.gridLayoutWidget)
        self.tentnoBar.setMaximum(200)
        self.tentnoBar.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.tentnoBar.setObjectName("tentnoBar")
        self.gridLayout.addWidget(self.tentnoBar, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.tentoBox = QtWidgets.QSpinBox(parent=self.gridLayoutWidget)
        self.tentoBox.setMaximum(200)
        self.tentoBox.setObjectName("tentoBox")
        self.gridLayout.addWidget(self.tentoBox, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.wiekBox = QtWidgets.QSpinBox(parent=self.gridLayoutWidget)
        self.wiekBox.setMaximum(100)
        self.wiekBox.setObjectName("wiekBox")
        self.gridLayout.addWidget(self.wiekBox, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.cholBar = QtWidgets.QScrollBar(parent=self.gridLayoutWidget)
        self.cholBar.setMinimum(100)
        self.cholBar.setMaximum(300)
        self.cholBar.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.cholBar.setObjectName("cholBar")
        self.gridLayout.addWidget(self.cholBar, 1, 1, 1, 1)
        self.cholBox = QtWidgets.QSpinBox(parent=self.gridLayoutWidget)
        self.cholBox.setMinimum(100)
        self.cholBox.setMaximum(300)
        self.cholBox.setObjectName("cholBox")
        self.gridLayout.addWidget(self.cholBox, 1, 2, 1, 1)
        self.wiekBar = QtWidgets.QSlider(parent=self.gridLayoutWidget)
        self.wiekBar.setMaximum(100)
        self.wiekBar.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.wiekBar.setObjectName("wiekBar")
        self.gridLayout.addWidget(self.wiekBar, 2, 1, 1, 1)
        self.progress = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.progress.setObjectName("progress")
        self.gridLayout.addWidget(self.progress, 3, 2, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(parent=self.gridLayoutWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 3, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "Wiek [lat]"))
        self.label_2.setText(_translate("Dialog", "Choresterol całkowity [mg/dl]"))
        self.label.setText(_translate("Dialog", "Tętno [uderzen/min]"))
        self.label_4.setText(_translate("Dialog", "Szansa na przeżycie [%]"))
        self.progress.setText(_translate("Dialog", "😎"))
